[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"

[profile.default.fmt]
line_length = 120

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
